### ISSUE TITLE
[Web Bug] - AWS Quickstart Part 2

### ISSUE THREAD

**Issue by cassamajor** [crossplane/docs#356]
URL: /v1.11/getting-started/provider-aws-part-2/

1. Composition definition starts with `dynamodb-with-s3`, and later the examples switch to `dynamo-with-bucket`.

2. When defining the XRD, the name is `databases.custom-api.example.org`, then later defined as `custom-api-definition`, then later again as `xdatabases.custom-api.example.org`.

URL: /v1.11/getting-started/provider-aws-part-2/#apply-the-composite-resource-definition

3. `plural` is missing the `X`. 
```
spec:
  group: custom-api.example.org
  names:
    kind: XDatabase
    plural: databases
```

URL: /v1.11/getting-started/provider-aws-part-2/#define-a-composite-resource

4. The `Define a composite resource` section would be more accurate if it was titled `Define a composite resource definition`. I think would would be more grammatically appropriate if it was capitalized as `Define a Composite Resource Definition`.

**Comment by cassamajor** [comment]
Not a bug, but a question:

Why suggest `kubectl explain compositeresourcedefinitions`  instead of `kubectl explain xrd`?

**Comment by plumbis** [comment]
>The Define a composite resource section would be more accurate ...

My thinking was that the goal is to define a composite resource which is a natural extension from an _MR_, but in the process introduce a _CompositeResourceDefinition_ .  Happy to take feedback on this.

>Why suggest `kubectl explain ...` 

This has been updated

**Comment by plumbis** [comment]
I pushed a fix for this, would you be interested in reviewing the update? 

https://deploy-preview-357--crossplane.netlify.app/v1.11/getting-started/provider-aws/

**Comment by cassamajor** [comment]
The XRD exists with three different names:
1. `databases.custom-api.example.org`
2. `custom-api-definition`
3. `xdatabases.custom-api.example.org`

It is unclear to me whether 1 or 3 is the correct name.

**Comment by cassamajor** [comment]
> My thinking was that the goal is to define a composite resource which is a natural extension from an _MR_, but in the process introduce a _CompositeResourceDefinition_ . Happy to take feedback on this.

Personal Option: the section should be titled according to what action is being taken. The action being taken in this section is defining the XRD. The top level sections in the document are:
* [Create a composition](https://docs.crossplane.io/v1.11/getting-started/provider-aws-part-2/#create-a-composition)
* [Define a composite resource](https://docs.crossplane.io/v1.11/getting-started/provider-aws-part-2/#define-a-composite-resource)
* [Create a composite resource](https://docs.crossplane.io/v1.11/getting-started/provider-aws-part-2/#create-a-composite-resource)
 * [Create a claim](https://docs.crossplane.io/v1.11/getting-started/provider-aws-part-2/#create-a-claim)

So, to that avail, the section should probably be named `Define a Composite Resource Definition`.

**Comment by cassamajor** [comment]
I also noticed the second bug I mentioned is still present. The XRD still exists with three different names:
1. `databases.custom-api.example.org`
2. `custom-api-definition`
3. `xdatabases.custom-api.example.org`

It is unclear to me whether the first or third is the correct name.

**Comment by cassamajor** [comment]
And `kubectl explain compositeresourcedefinitions` was modified to `kubectl explain compositeresourcedefinition` instead of `kubectl explain xrd`

**Comment by bobh66** [comment]
> My thinking was that the goal is to define a composite resource which is a natural extension from an MR, but in the process introduce a CompositeResourceDefinition . Happy to take feedback on this.

This does make sense from an introductory standpoint, but I tend to think of it the other way around.  I have a thing that I want to abstract which is a collection of Managed Resources, and I start with the Composite Resource Definition to define the high level API/abstraction of the thing that I want.  This is my XDatabase XRD and has a set of parameters and output status attributes, which may need to change once I implement the Composition, but it's a first pass.  That defines the "umbrella" that I want to work within, and then I create the Composition with all of the required Managed Resources to implement the abstraction.

My only concern with the current flow is that the Composition is initially referencing something (XDatabase) that doesn't exist yet, which could be confusing.   By defining the XRD first and then the Composition that implements it, you don't end up referencing things before they exist,

I don't think there is one right answer - the introduction is necessarily more simplistic than the advanced usage.  I do think it's important to focus on the definition of the abstraction (XRD) since that is Crossplane's main reason for being.

**Comment by plumbis** [comment]
Thanks @bobh66 . Nic had somewhat similar feedback. 

When writing this I tried to take a "I'm trying to manage resources and build from there" view instead of a "I want to create a custom platform API". The main reason is about how much "net new" stuff is being introduce. If we start with XRDs and the custom API definitions we're asking readers with no custom platform exposure to suspend belief until they can connect their custom API to the resources it creates. Kind of a "top down" vs "bottoms up" approach. 

It's something we'll have to be mindful of reader feedback to see if this works or if we need to change things up. 

I also think (hope?) that as the more advanced chapters around the [concepts](https://docs.crossplane.io/v1.11/concepts/) get updated and expanded it will make this less of a problem.

**Comment by plumbis** [comment]
@cassamajor

**Comment by plumbis** [comment]
> And kubectl explain compositeresourcedefinitions was modified to kubectl explain compositeresourcedefinition instead of kubectl explain xrd


this was done on purpose to try and reduce the use of acronyms to be more explicit and obvious

**Comment by cassamajor** [comment]
## AWS Quickstart Part 2
1. databases.custom-api.example.org
    - https://github.com/plumbis/crossplane-docs/blob/85c546c8c729c9dcdeddb8e9e66c078adb3d333e/content/v1.11/getting-started/provider-aws-part-2.md?plain=1#L356
    - https://github.com/plumbis/crossplane-docs/blob/85c546c8c729c9dcdeddb8e9e66c078adb3d333e/content/v1.11/getting-started/provider-aws-part-2.md?plain=1#L373
2. custom-api-definition
    - https://github.com/plumbis/crossplane-docs/blob/85c546c8c729c9dcdeddb8e9e66c078adb3d333e/content/v1.11/getting-started/provider-aws-part-2.md?plain=1#L415
3. xdatabases.custom-api.example.org
    - https://github.com/plumbis/crossplane-docs/blob/85c546c8c729c9dcdeddb8e9e66c078adb3d333e/content/v1.11/getting-started/provider-aws-part-2.md?plain=1#L562
    - https://github.com/plumbis/crossplane-docs/blob/85c546c8c729c9dcdeddb8e9e66c078adb3d333e/content/v1.11/getting-started/provider-aws-part-2.md?plain=1#L597

## AWS Quickstart Part 3
1. databases.custom-api.example.org
    - https://github.com/plumbis/crossplane-docs/blob/85c546c8c729c9dcdeddb8e9e66c078adb3d333e/content/v1.11/getting-started/provider-aws-part-3.md?plain=1#L504
2. xdatabases.custom-api.example.org
    - https://github.com/plumbis/crossplane-docs/blob/85c546c8c729c9dcdeddb8e9e66c078adb3d333e/content/v1.11/getting-started/provider-aws-part-3.md?plain=1#L128

**Comment by plumbis** [comment]
alright, pushed another fix. Thank you for your help on this one, I missed it every time I looked.

**Comment by cassamajor** [comment]
Thank you, @plumbis -- looks good.

I agree with @bobh66's approach. Going through the tutorial in its first iteration, my thought was: "I do not understand these values or why I am constructing it in this way, but the tutorial says to do it so I will."

What I prefer when following tutorials: "The concepts and values were clearly defined, and I understand what each mean as I am following along."

If the tutorial is approached in a more foundational way (XRD -> Composition -> XR -> Claim) it would make it much more comprehensible. As an additional example, going from Composition -> XRD -> XR, I did not understand the relationship of how the XR used the Composition. Having the sections in closer order like suggested above may help alleviate this.

**Comment by cassamajor** [comment]
One more comment to look into before we mark this closed: https://github.com/crossplane/docs/pull/357#discussion_r1103738700

**Comment by cassamajor** [comment]
These issues were addressed in https://github.com/crossplane/docs/pull/360, so I am marking this issue closed.
